### ISSUE TITLE
This is not boilerplate Thomas?

### ISSUE THREAD

**Issue by aligos** [thomasdao/goal#1]
Sorry for asking in issue, but on readme file you write some code and the code have not file structur in this repo, i hope you create video documentation or write that on blog/medium.
Anyway thanks for creating this.

**Comment by thomasdao** [comment]
Hi @aligos , which file structure that you do not find in the repo? I will be using this project in production soon and hopefully make it mature enough for people to use.

**Comment by aligos** [comment]
i mean in Readme file, that code have not name file. can you give file name for every code section on readme file.
Thank's a million

**Comment by thomasdao** [comment]
you can use "Search" function from github to search for any code you need. It will give you the file contains that code
